import { describe, it, expect } from "vitest";

import { buildDiscoveryBriefingMarkdown } from "@/lib/discovery-briefing/markdown";
import {
  defaultDiscoveryBriefingState,
  type DiscoveryBriefingState,
} from "@/lib/discovery-briefing/types";

/**
 * Canonical empty-state output for the v3 discovery briefing renderer.
 *
 * Generated once by running the renderer against `defaultDiscoveryBriefingState()`
 * and copied verbatim. If you change the renderer's ordering or default
 * fallbacks, regenerate this constant and update it in lockstep.
 */
const EMPTY_STATE_MARKDOWN = [
  "# Client Discovery Briefing",
  "",
  "**Business:** Not provided",
  "**Website:** Not provided",
  "",
  "## Business Overview",
  "",
  "Not provided",
  "",
  "---",
  "",
  "## Core Services",
  "",
  "Not provided",
  "",
  "**Revenue split:** Not provided",
  "",
  "---",
  "",
  "## Target Audience",
  "",
  "**Ideal client:** Not provided",
  "**Locations:** Not provided",
  "**Geographic focus:** Not provided",
  "",
  "---",
  "",
  "## Commercials & Growth",
  "",
  "**Average order value:** Not provided",
  "**Purchase frequency (per client per year):** Not provided",
  "**Current new leads / month:** Not provided",
  "**Ideal lead volume / month:** Not provided",
  "**Top growth channel:** Not provided",
  "",
  "---",
  "",
  "## USP & Differentiation",
  "",
  "**USP:** Not provided",
  "",
  "**Differentiation:** Not provided",
  "",
  "---",
  "",
  "## Brand Assets & Voice",
  "",
  "**Logo / assets:** Not provided",
  "**Colours:** Not provided",
  "**Fonts:** Not provided",
  "**Style guide:** Not provided",
  "**Tone of voice:** Not provided",
  "**Reference sites / writing:** Not provided",
  "",
  "---",
  "",
  "## Tech Stack",
  "",
  "**CRM:** Not provided",
  "**Email:** Not provided",
  "**Calendar / scheduling:** Not provided",
  "**Project management:** Not provided",
  "**Payment processor:** Not provided",
  "**Communication / phone:** Not provided",
  "**CMS:** Not provided",
  "**Analytics:** Not provided",
  "",
  "**Other tools:** Not provided",
  "",
  "### Tools & Access",
  "",
  "- **Search Console:** Has it: not provided — Access: not provided",
  "- **GA4:** Has it: not provided — Access: not provided",
  "- **GTM:** Has it: not provided — Access: not provided",
  "- **Hosting:** Has it: not provided — Access: not provided",
  "- **DNS:** Has it: not provided — Access: not provided",
  "- **Backlinks tool:** Has it: not provided — Access: not provided",
  "- **Review platforms:** Has it: not provided — Access: not provided",
  "",
  "---",
  "",
  "## Current SEO & Online Presence",
  "",
  "**Google Business Profile:** Not specified",
  "**Social media:** None specified",
  "",
  "---",
  "",
  "## Social Proof",
  "",
  "**Notable clients:** Not provided",
  "",
  "**Notable individuals:** Not provided",
  "",
  "**Reviews:** Not specified",
  "",
  "---",
  "",
  "## Content Strategy",
  "",
  "**Content focus:** Not specified",
  "",
  "**Topics & angles the audience cares about:** Not provided",
  "",
  "---",
  "",
  "## Google Ads",
  "",
  "**Status:** Not provided",
  "**Budget:** Not provided",
  "",
  "**Campaigns:** Not provided",
  "**Average CPC:** Not provided",
  "**Expected conversion rate:** Not provided",
  "",
  "---",
  "",
  "## Timeline",
  "",
  "**Launch date:** Not provided",
  "",
  "**Deadlines:** Not provided",
  "",
  "---",
  "",
  "## Working Relationship",
  "",
  "**Point of contact (changes, approvals, asset requests):** Not provided",
  "",
  "---",
  "",
  "## Lead Nurturing",
  "",
  "**Current process:** Not provided",
  "",
  "**Future-state notes:** Not provided",
  "",
  "---",
  "",
  "## Discovery Notes",
  "",
  "**Additional notes:** Not provided",
  "",
  "**Questions for us:** Not provided",
  "",
  "**Internal notes:** Not provided",
  "",
  "",
  "---",
  "",
  "*Generated by Optimise Digital — Client Discovery Briefing*",
].join("\n");

function filledState(): DiscoveryBriefingState {
  return {
    ...defaultDiscoveryBriefingState(),
    businessName: "Acme Widgets",
    websiteUrl: "https://acme.example",
    oneLiner: "We sell premium widgets to enterprise buyers.",
    services: [
      { name: "Widget Design", highMargin: true, focus: true },
      { name: "Widget Repair", highMargin: false, focus: false },
      { name: "", highMargin: false, focus: true }, // exercises "Unnamed" fallback
    ],
    revenueSplit: "60% design / 40% repair",
    specialisms: "Custom titanium widgets",
    idealClient: "Mid-market manufacturers",
    locations: "Sydney, Melbourne",
    geoFocus: "national",
    industries: ["healthcare", "finance", "other"],
    industryOther: "Aerospace",
    usp: "30-day money-back guarantee",
    competitorsAdmire: "WidgetCo, BoltWorks",
    differentiators: "In-house metallurgy team",
    brandLogoNotes: "Drive: drive.google.com/acme-logos",
    brandColors: "#1A1A1A primary, #2563EB accent",
    brandFonts: "Inter, Söhne",
    brandStyleGuideUrl: "https://acme.example/brand",
    brandToneOfVoice: ["Authoritative", "Friendly", "other"],
    brandToneOfVoiceOther: "Slightly nerdy",
    brandReferenceSites: "basecamp.com, stripe.com",
    crm: "other",
    crmOther: "Folk",
    emailMarketing: "mailchimp",
    calendarScheduling: "calendly",
    projectManagement: "linear",
    paymentProcessor: "stripe",
    communication: "slack",
    cms: "payload",
    analytics: "ga4",
    otherTools: "Notion, Figma",
    toolSearchConsoleStatus: "yes",
    toolSearchConsoleAccess: "yes",
    toolGa4Status: "yes",
    toolGa4Access: "later",
    toolGtmStatus: "no",
    toolGtmAccess: "no",
    toolHostingStatus: "yes",
    toolHostingAccess: "later",
    toolHostingProvider: "Cloudflare Pages",
    toolDnsStatus: "unsure",
    toolDnsAccess: "no",
    toolDnsProvider: "GoDaddy",
    toolBacklinksStatus: "yes",
    toolBacklinksAccess: "yes",
    toolBacklinksTool: "Ahrefs",
    toolReviewsStatus: "yes",
    toolReviewsAccess: "yes",
    toolReviewsPlatforms: "Trustpilot, ProductReview.com.au",
    prDone: "yes",
    prDetails: "AFR feature, March 2025",
    existingBacklinksNotes: "forbes.com link from 2022",
    linkedDeckSlug: "acme-proposal-v2",
    gbpExists: true,
    gbpPartial: false,
    gbpNone: false,
    gbpUpdateDetails: true,
    gbpRespondReviews: true,
    gbpPostRegularly: false,
    socialLinkedin: true,
    socialLinkedinHandle: "@acme",
    socialFacebook: true,
    socialFacebookHandle: "",
    socialInstagram: false,
    socialInstagramHandle: "@ignored",
    socialYoutube: true,
    socialYoutubeHandle: "@acmevideos",
    notableClients: "BigCo, MegaCorp",
    notableIndividuals: "Jane Doe, CEO",
    proof: [
      { client: "BigCo", testimonial: "Best widgets ever.", useOnSite: true },
      { client: "", testimonial: "", useOnSite: false },
      { client: "MegaCorp", testimonial: "", useOnSite: false },
    ],
    reviewsGoogle: true,
    reviewsClutch: true,
    pillarTopics: [
      { name: "Titanium widgets 101" },
      { name: "" },
      { name: "Buying guides" },
    ],
    faqs: [
      { question: "Do you ship internationally?", answer: "Yes, DHL Express." },
      { question: "", answer: "" },
      { question: "Warranty?", answer: "" },
    ],
    seoGoal: "leads",
    targetKeywords: "titanium widgets, custom widgets",
    contentBlog: true,
    contentCaseStudies: true,
    contentServicePages: true,
    adsStatus: "active",
    adsBudget: "$5k/mo",
    adsCampaigns: "Brand + Generic",
    negativeKeywords: "cheap, free",
    websiteBudget: "10k-20k",
    seoBudget: "3k-5k",
    launchDate: "2026-07-01",
    deadlines: "Q3 launch",
    additionalNotes: "Big plans for Q4.",
    questionsForUs: "Can you handle Spanish content?",
    internalNotes: "High-priority deal.",
    complianceNotes: "TGA-regulated copy review required.",
    decisionMakerNotes: "Jane (CEO) approves; cycle ~2 weeks.",
    hostingDnsNotes: "DNS managed via GoDaddy; hosting via Cloudflare.",
    audienceSegments: [
      {
        name: "Personal",
        averageOrderValue: "$120",
        purchaseFrequency: "4",
        newLeadsPerMonth: "30",
        idealLeadVolume: "80",
      },
      {
        name: "Business customers",
        averageOrderValue: "$4,500",
        purchaseFrequency: "2",
        newLeadsPerMonth: "5",
        idealLeadVolume: "20",
      },
    ],
    leadMagnets: [
      {
        name: "Free SEO audit",
        description: "Personalised audit PDF",
        cta: "/audit",
      },
      { name: "Pricing guide", description: "", cta: "" },
    ],
    leadMagnetsNotes: "Run paid social to push the audit magnet first.",
    raciRows: [
      {
        task: "Ad creative",
        responsible: "Designer",
        accountable: "Marketing lead",
        consulted: "Sales",
        informed: "CEO",
      },
      {
        task: "Approve copy",
        responsible: "Copywriter",
        accountable: "Marketing lead",
        consulted: "",
        informed: "",
      },
    ],
    approvalsNotes: "CEO signs off on monthly ad spend > $10k.",
    hiddenSections: [],
  };
}

describe("buildDiscoveryBriefingMarkdown", () => {
  it("renders the canonical empty-state skeleton with all `Not provided` fallbacks", () => {
    const state = defaultDiscoveryBriefingState();
    const md = buildDiscoveryBriefingMarkdown(state);
    expect(md).toBe(EMPTY_STATE_MARKDOWN);
  });

  it("starts with the discovery briefing title and footer marker", () => {
    const md = buildDiscoveryBriefingMarkdown(defaultDiscoveryBriefingState());
    expect(md.startsWith("# Client Discovery Briefing\n")).toBe(true);
    expect(md.endsWith("*Generated by Optimise Digital — Client Discovery Briefing*")).toBe(
      true,
    );
  });

  it("includes every section heading in order for a filled state", () => {
    const md = buildDiscoveryBriefingMarkdown(filledState());
    const expectedHeadings = [
      "# Client Discovery Briefing",
      "## Business Overview",
      "## Core Services",
      "## Target Audience",
      "## Commercials & Growth",
      "## USP & Differentiation",
      "## Brand Assets & Voice",
      "## Tech Stack",
      "### Tools & Access",
      "## Current SEO & Online Presence",
      "## Social Proof",
      "## Lead Magnets",
      "## Content Strategy",
      "## Google Ads",
      "## Timeline",
      "## Working Relationship",
      "## RACI & Approvals",
      "## Lead Nurturing",
      "## Discovery Notes",
      "## Additional Details",
    ];
    let lastIdx = -1;
    for (const heading of expectedHeadings) {
      const idx = md.indexOf(heading);
      expect(idx, `heading "${heading}" missing or out of order`).toBeGreaterThan(lastIdx);
      lastIdx = idx;
    }
  });

  it("renders the dynamic services list with margin and focus annotations", () => {
    const md = buildDiscoveryBriefingMarkdown(filledState());
    expect(md).toContain("- Widget Design (high margin) — priority focus");
    expect(md).toContain("- Widget Repair");
    // Empty name falls back to "Unnamed", focus flag still rendered
    expect(md).toContain("- Unnamed — priority focus");
    // No bare "Not provided" line in the services section
    const servicesSection = md.split("## Core Services")[1]?.split("---")[0] ?? "";
    expect(servicesSection).not.toContain("Not provided\n");
  });

  it("renders the testimonials subsection only for rows with content", () => {
    const md = buildDiscoveryBriefingMarkdown(filledState());
    expect(md).toContain("### Testimonials / Case Studies");
    // useOnSite=true row gets the website-use suffix
    expect(md).toContain("- **BigCo:** Best widgets ever. — OK to use on website");
    // useOnSite=false row has no suffix
    expect(md).toContain("- **MegaCorp:** ");
    expect(md).not.toContain("- **MegaCorp:**  — OK to use on website");
    // The fully-empty row must be skipped
    expect(md).not.toMatch(/-\s+\*\*Client:\*\*\s*\n/);
  });

  it("joins industries and renders the `other` override", () => {
    const md = buildDiscoveryBriefingMarkdown(filledState());
    expect(md).toContain("**Industries:** healthcare, finance, Other: Aerospace");
  });

  it("renders selected social networks and only handles where the toggle is on", () => {
    const md = buildDiscoveryBriefingMarkdown(filledState());
    expect(md).toContain("**Social media:** LinkedIn, Facebook, YouTube");
    expect(md).toContain("**Social handles:** LinkedIn: @acme · YouTube: @acmevideos");
    // Instagram handle is set but toggle is off → must NOT appear
    expect(md).not.toContain("Instagram: @ignored");
    // Facebook handle is empty so it must not appear in handles either
    expect(md).not.toMatch(/Facebook:\s+(?=·|$)/m);
  });

  it("renders GBP follow-ups only when at least one GBP option is selected", () => {
    const filled = buildDiscoveryBriefingMarkdown(filledState());
    expect(filled).toContain("**Google Business Profile:** Claimed and optimised");
    expect(filled).toContain("  - Keeps business details up to date");
    expect(filled).toContain("  - Responds to reviews");
    expect(filled).not.toContain("  - Posts regularly");

    // With no GBP options selected, follow-ups must not appear
    const noGbp: DiscoveryBriefingState = {
      ...defaultDiscoveryBriefingState(),
      gbpUpdateDetails: true,
      gbpRespondReviews: true,
      gbpPostRegularly: true,
    };
    const noGbpMd = buildDiscoveryBriefingMarkdown(noGbp);
    expect(noGbpMd).toContain("**Google Business Profile:** Not specified");
    expect(noGbpMd).not.toContain("  - Keeps business details up to date");
    expect(noGbpMd).not.toContain("  - Responds to reviews");
    expect(noGbpMd).not.toContain("  - Posts regularly");
  });

  it("appends the `other` value to tech-stack rows only when value === 'other'", () => {
    const md = buildDiscoveryBriefingMarkdown(filledState());
    expect(md).toContain("**CRM:** other — Folk");
    expect(md).toContain("**Email:** mailchimp");
    // No stray em-dash when value is not "other"
    expect(md).not.toContain("**Email:** mailchimp — ");
  });

  it("renders the Commercials & Growth section with all filled legacy values when no audience segments", () => {
    const state: DiscoveryBriefingState = {
      ...defaultDiscoveryBriefingState(),
      averageOrderValue: "$2,500",
      purchaseFrequency: "3",
      newLeadsPerMonth: "20",
      idealLeadVolume: "60",
      topGrowthChannel: "referrals",
    };
    const md = buildDiscoveryBriefingMarkdown(state);
    expect(md).toContain("## Commercials & Growth");
    expect(md).toContain("**Average order value:** $2,500");
    expect(md).toContain("**Purchase frequency (per client per year):** 3");
    expect(md).toContain("**Current new leads / month:** 20");
    expect(md).toContain("**Ideal lead volume / month:** 60");
    // Legacy single-string field still renders when topGrowthChannels is empty
    expect(md).toContain("**Top growth channel:** referrals");
  });

  it("renders multi-audience subsections under Commercials when audienceSegments is populated", () => {
    const md = buildDiscoveryBriefingMarkdown(filledState());
    expect(md).toContain("## Commercials & Growth");
    expect(md).toContain("### Personal");
    expect(md).toContain("### Business customers");
    // Each segment's values render
    expect(md).toContain("**Average order value:** $120");
    expect(md).toContain("**Average order value:** $4,500");
    expect(md).toContain("**Current new leads / month:** 30");
    expect(md).toContain("**Ideal lead volume / month:** 20");
  });

  it("falls back to legacy 4-line layout when audienceSegments is empty", () => {
    const state: DiscoveryBriefingState = {
      ...defaultDiscoveryBriefingState(),
      averageOrderValue: "$1,000",
      audienceSegments: [],
    };
    const md = buildDiscoveryBriefingMarkdown(state);
    expect(md).toContain("**Average order value:** $1,000");
    // No segment subsections
    expect(md).not.toMatch(/^### [^#\n]+\n\*\*Average order value:\*\*/m);
  });

  it("renders ranked topGrowthChannels list with selection-order numbering", () => {
    const state: DiscoveryBriefingState = {
      ...defaultDiscoveryBriefingState(),
      topGrowthChannels: ["referrals", "organic", "paid_search"],
    };
    const md = buildDiscoveryBriefingMarkdown(state);
    expect(md).toContain(
      "**Top growth channels (ranked):** 1. referrals, 2. organic, 3. paid_search",
    );
  });

  it("renders the `Other` override for ranked topGrowthChannels", () => {
    const state: DiscoveryBriefingState = {
      ...defaultDiscoveryBriefingState(),
      topGrowthChannels: ["referrals", "other"],
      topGrowthChannelOther: "In-person networking",
    };
    const md = buildDiscoveryBriefingMarkdown(state);
    expect(md).toContain(
      "**Top growth channels (ranked):** 1. referrals, 2. Other: In-person networking",
    );
  });

  it("renders the `Other` override for legacy topGrowthChannel", () => {
    const state: DiscoveryBriefingState = {
      ...defaultDiscoveryBriefingState(),
      topGrowthChannel: "other",
      topGrowthChannelOther: "In-person networking",
    };
    const md = buildDiscoveryBriefingMarkdown(state);
    expect(md).toContain("**Top growth channel:** Other: In-person networking");
  });

  it("renders the populated reviews and content-focus lists", () => {
    const md = buildDiscoveryBriefingMarkdown(filledState());
    expect(md).toContain("**Reviews:** Google Reviews, Clutch/Industry");
    // contentServicePages is no longer rendered
    expect(md).toContain("**Content focus:** Blog posts, Case studies");
    expect(md).not.toContain("Service pages");
  });

  it("renders the Working Relationship and Lead Nurturing sections", () => {
    const state: DiscoveryBriefingState = {
      ...defaultDiscoveryBriefingState(),
      pointOfContact: "Jane Doe (CMO)",
      leadNurturingSteps: [
        { step: "Lead form submitted", owner: "Website" },
        { step: "Welcome email", owner: "Mailchimp" },
        { step: "", owner: "" }, // empty row — should be skipped
        { step: "Sales call", owner: "Account exec" },
      ],
      leadNurturingFutureNotes: "Add SMS reminders and CRM scoring.",
    };
    const md = buildDiscoveryBriefingMarkdown(state);
    expect(md).toContain("## Working Relationship");
    expect(md).toContain(
      "**Point of contact (changes, approvals, asset requests):** Jane Doe (CMO)",
    );
    expect(md).toContain("## Lead Nurturing");
    expect(md).toContain("### Current process");
    expect(md).toContain("1. Lead form submitted — Website");
    expect(md).toContain("2. Welcome email — Mailchimp");
    // empty row is skipped, but indices use original positions
    expect(md).toContain("4. Sales call — Account exec");
    expect(md).not.toContain("3. Unnamed step");
    expect(md).toContain(
      "**Future-state notes:** Add SMS reminders and CRM scoring.",
    );
  });

  it("estimates monthly leads when budget, CPC, and conversion rate parse cleanly", () => {
    const state: DiscoveryBriefingState = {
      ...defaultDiscoveryBriefingState(),
      adsBudget: "$5000",
      adsAvgCpc: "$2.50",
      adsConversionRate: "4",
    };
    const md = buildDiscoveryBriefingMarkdown(state);
    // 5000 / 2.50 = 2000 clicks * 4% = 80 leads
    expect(md).toContain("**Estimated leads / month:** 80");
  });

  it("omits the leads estimate when any calculator input is missing or non-numeric", () => {
    const state: DiscoveryBriefingState = {
      ...defaultDiscoveryBriefingState(),
      adsBudget: "$5000",
      adsAvgCpc: "",
      adsConversionRate: "4",
    };
    const md = buildDiscoveryBriefingMarkdown(state);
    expect(md).not.toContain("**Estimated leads / month:**");
  });

  it("renders the Brand Assets & Voice section with the `Other` tone override", () => {
    const md = buildDiscoveryBriefingMarkdown(filledState());
    expect(md).toContain("## Brand Assets & Voice");
    expect(md).toContain("**Logo / assets:** Drive: drive.google.com/acme-logos");
    expect(md).toContain("**Colours:** #1A1A1A primary, #2563EB accent");
    expect(md).toContain("**Fonts:** Inter, Söhne");
    expect(md).toContain("**Style guide:** https://acme.example/brand");
    expect(md).toContain(
      "**Tone of voice:** Authoritative, Friendly, Other: Slightly nerdy",
    );
    expect(md).toContain(
      "**Reference sites / writing:** basecamp.com, stripe.com",
    );
  });

  it("renders the Tools & Access subsection with status, access, and provider extras but no PR/backlinks bullets", () => {
    const md = buildDiscoveryBriefingMarkdown(filledState());
    expect(md).toContain("### Tools & Access");
    expect(md).toContain(
      "- **Search Console:** Has it: yes — Access: granted",
    );
    expect(md).toContain("- **GA4:** Has it: yes — Access: will provide later");
    expect(md).toContain("- **GTM:** Has it: no — Access: not yet");
    expect(md).toContain(
      "- **Hosting:** Has it: yes — Access: will provide later — Provider: Cloudflare Pages",
    );
    expect(md).toContain(
      "- **DNS:** Has it: not sure — Access: not yet — Provider: GoDaddy",
    );
    expect(md).toContain(
      "- **Backlinks tool:** Has it: yes — Access: granted — Tool: Ahrefs",
    );
    expect(md).toContain(
      "- **Review platforms:** Has it: yes — Access: granted — Platforms: Trustpilot, ProductReview.com.au",
    );
    // PR + backlinks should NOT appear inside Tools & Access anymore
    const toolsBlock = md.split("### Tools & Access")[1]?.split("---")[0] ?? "";
    expect(toolsBlock).not.toContain("- **PR done:**");
    expect(toolsBlock).not.toContain("- **Existing backlinks to protect:**");
  });

  it("renders PR done + backlinks lines inside Social Proof when populated", () => {
    const md = buildDiscoveryBriefingMarkdown(filledState());
    const socialProofBlock =
      md.split("## Social Proof")[1]?.split("\n## ")[0] ?? "";
    expect(socialProofBlock).toContain("**PR done:** yes — AFR feature, March 2025");
    expect(socialProofBlock).toContain(
      "**Existing backlinks to protect:** forbes.com link from 2022",
    );
  });

  it("omits PR done + backlinks lines from Social Proof when empty", () => {
    const md = buildDiscoveryBriefingMarkdown(defaultDiscoveryBriefingState());
    expect(md).not.toContain("**PR done:**");
    expect(md).not.toContain("**Existing backlinks to protect:**");
  });

  it("renders the Pillar Topics numbered list, skipping empty rows", () => {
    const md = buildDiscoveryBriefingMarkdown(filledState());
    expect(md).toContain("### Pillar Topics");
    expect(md).toContain("1. Titanium widgets 101");
    expect(md).toContain("2. Buying guides");
    expect(md).not.toContain("3.");
  });

  it("omits Pillar Topics subsection when no rows have content", () => {
    const state: DiscoveryBriefingState = {
      ...defaultDiscoveryBriefingState(),
      pillarTopics: [{ name: "" }, { name: "   " }],
    };
    const md = buildDiscoveryBriefingMarkdown(state);
    expect(md).not.toContain("### Pillar Topics");
  });

  it("renders the FAQs subsection only for rows with at least one non-empty field", () => {
    const md = buildDiscoveryBriefingMarkdown(filledState());
    expect(md).toContain("### FAQs");
    expect(md).toContain("**Q:** Do you ship internationally?");
    expect(md).toContain("**A:** Yes, DHL Express.");
    expect(md).toContain("**Q:** Warranty?");
    // Empty row entirely skipped, question-only row still rendered with blank A
  });

  it("omits the FAQs subsection when no row has any content", () => {
    const state: DiscoveryBriefingState = {
      ...defaultDiscoveryBriefingState(),
      faqs: [{ question: "", answer: "" }],
    };
    const md = buildDiscoveryBriefingMarkdown(state);
    expect(md).not.toContain("### FAQs");
  });

  it("renders the Linked proposal deck line under Working Relationship only when set", () => {
    const filled = buildDiscoveryBriefingMarkdown(filledState());
    expect(filled).toContain("**Linked proposal deck:** acme-proposal-v2");

    const empty = buildDiscoveryBriefingMarkdown(defaultDiscoveryBriefingState());
    expect(empty).not.toContain("**Linked proposal deck:**");
  });

  it("renders the Additional Details section only when complianceNotes is non-empty", () => {
    const filled = buildDiscoveryBriefingMarkdown(filledState());
    expect(filled).toContain("## Additional Details");
    expect(filled).toContain(
      "**Compliance notes:** TGA-regulated copy review required.",
    );
    // Legacy decision-maker / hosting-DNS notes are no longer rendered
    expect(filled).not.toContain("**Decision-maker");
    expect(filled).not.toContain("**Hosting / DNS notes:**");
  });

  it("omits the Additional Details section when complianceNotes is empty", () => {
    const state: DiscoveryBriefingState = {
      ...defaultDiscoveryBriefingState(),
      decisionMakerNotes: "Jane (CEO)",
      hostingDnsNotes: "GoDaddy",
    };
    const md = buildDiscoveryBriefingMarkdown(state);
    expect(md).not.toContain("## Additional Details");
  });

  it("renders Lead Magnets only when at least one row or notes is populated", () => {
    const filled = buildDiscoveryBriefingMarkdown(filledState());
    expect(filled).toContain("## Lead Magnets");
    expect(filled).toContain(
      "- **Free SEO audit** — Personalised audit PDF (CTA: /audit)",
    );
    // Row with only a name still renders
    expect(filled).toContain("- **Pricing guide**");
    expect(filled).toContain(
      "**Notes:** Run paid social to push the audit magnet first.",
    );

    const empty = buildDiscoveryBriefingMarkdown(defaultDiscoveryBriefingState());
    expect(empty).not.toContain("## Lead Magnets");
  });

  it("renders Lead Magnets notes-only when there are no rows", () => {
    const state: DiscoveryBriefingState = {
      ...defaultDiscoveryBriefingState(),
      leadMagnetsNotes: "Just a strategy note, no concrete magnets yet.",
    };
    const md = buildDiscoveryBriefingMarkdown(state);
    expect(md).toContain("## Lead Magnets");
    expect(md).toContain(
      "**Notes:** Just a strategy note, no concrete magnets yet.",
    );
  });

  it("renders RACI & Approvals only when at least one row or notes is populated", () => {
    const filled = buildDiscoveryBriefingMarkdown(filledState());
    expect(filled).toContain("## RACI & Approvals");
    expect(filled).toContain(
      "- **Ad creative:** R: Designer; A: Marketing lead; C: Sales; I: CEO",
    );
    // Row with blanks omits empty pieces
    expect(filled).toContain(
      "- **Approve copy:** R: Copywriter; A: Marketing lead",
    );
    expect(filled).toContain(
      "**Approvals:** CEO signs off on monthly ad spend > $10k.",
    );

    const empty = buildDiscoveryBriefingMarkdown(defaultDiscoveryBriefingState());
    expect(empty).not.toContain("## RACI & Approvals");
  });

  it("renders RACI notes-only when there are no task rows", () => {
    const state: DiscoveryBriefingState = {
      ...defaultDiscoveryBriefingState(),
      approvalsNotes: "Just notes.",
    };
    const md = buildDiscoveryBriefingMarkdown(state);
    expect(md).toContain("## RACI & Approvals");
    expect(md).toContain("**Approvals:** Just notes.");
  });

  it("hiddenSections drops a section heading and its preceding rule", () => {
    const state: DiscoveryBriefingState = {
      ...defaultDiscoveryBriefingState(),
      adsStatus: "active",
      hiddenSections: ["googleAds"],
    };
    const md = buildDiscoveryBriefingMarkdown(state);
    expect(md).not.toContain("## Google Ads");
    expect(md).not.toContain("**Status:** active");
    // No double horizontal rule artifact left where Google Ads used to be
    expect(md).not.toMatch(/---\n\n---/);
  });

  it("omits the competitorsAdmire line when empty but renders it when populated", () => {
    const empty = buildDiscoveryBriefingMarkdown(defaultDiscoveryBriefingState());
    expect(empty).not.toContain("**Competitors you admire or want to mimic:**");

    const state: DiscoveryBriefingState = {
      ...defaultDiscoveryBriefingState(),
      competitorsAdmire: "Acme, Globex",
    };
    const md = buildDiscoveryBriefingMarkdown(state);
    expect(md).toContain(
      "**Competitors you admire or want to mimic:** Acme, Globex",
    );
  });

  it("renders every filled scalar field verbatim", () => {
    const state = filledState();
    const md = buildDiscoveryBriefingMarkdown(state);
    const checks: Array<[label: string, expected: string]> = [
      ["business", `**Business:** ${state.businessName}`],
      ["website", `**Website:** ${state.websiteUrl}`],
      ["oneLiner", state.oneLiner],
      ["revenueSplit", `**Revenue split:** ${state.revenueSplit}`],
      ["idealClient", `**Ideal client:** ${state.idealClient}`],
      ["locations", `**Locations:** ${state.locations}`],
      ["geoFocus", `**Geographic focus:** ${state.geoFocus}`],
      ["usp", `**USP:** ${state.usp}`],
      ["competitorsAdmire", `**Competitors you admire or want to mimic:** ${state.competitorsAdmire}`],
      ["differentiators", `**Differentiation:** ${state.differentiators}`],
      ["otherTools", `**Other tools:** ${state.otherTools}`],
      ["notableClients", `**Notable clients:** ${state.notableClients}`],
      ["notableIndividuals", `**Notable individuals:** ${state.notableIndividuals}`],
      ["adsStatus", `**Status:** ${state.adsStatus}`],
      ["adsBudget", `**Budget:** ${state.adsBudget}`],
      ["adsCampaigns", `**Campaigns:** ${state.adsCampaigns}`],
      ["launchDate", `**Launch date:** ${state.launchDate}`],
      ["deadlines", `**Deadlines:** ${state.deadlines}`],
      ["additionalNotes", `**Additional notes:** ${state.additionalNotes}`],
      ["questionsForUs", `**Questions for us:** ${state.questionsForUs}`],
      ["internalNotes", `**Internal notes:** ${state.internalNotes}`],
    ];
    for (const [label, expected] of checks) {
      expect(md, `field ${label} missing`).toContain(expected);
    }
  });
});
