import type { CollectionConfig } from "payload";
import { canAccess, hideUnlessFeature } from "../lib/access";

/**
 * Invoice Statement Drafts.
 *
 * Aggregated outstanding-invoice statement emails generated by the monthly
 * sweep cron (`/api/invoice-statements/sweep` on the 2nd of each month).
 *
 * Lifecycle:
 *   1. Sweep creates rows in `pending` for any Xero contact with \u22652 unpaid
 *      invoices. Snapshot of contact + invoices is frozen in `snapshot` JSON.
 *   2. Agency reviews in `/admin/finance/invoice-statements`, edits the
 *      optional `customMessage`, clicks Approve & Send.
 *   3. Approve-send route runs safety caps, fetches PDFs, sends via Postmark,
 *      sets `status='approved'` + `sentAt` + `postmarkMessageId` + `ccList`.
 *   4. Failed sends flip to `status='failed'` with `sendError` and surface
 *      with a Retry button.
 *   5. Pending rows older than 14 days are auto-expired by the next sweep.
 *
 * Idempotency: a `beforeChange` hook prevents two `pending` rows for the
 * same `xeroContactId`. The sweep route uses this to safely re-run within
 * a month.
 */
export const InvoiceStatementDrafts: CollectionConfig = {
  slug: "invoice-statement-drafts" as never,
  labels: {
    singular: "Invoice Statement Draft",
    plural: "Invoice Statement Drafts",
  },
  admin: {
    group: "Finance",
    useAsTitle: "contactName",
    defaultColumns: [
      "contactName",
      "status",
      "unpaidCount",
      "totalOutstanding",
      "totalOverdue",
      "generatedAt",
      "sentAt",
    ],
    listSearchableFields: ["contactName", "recipientEmail"],
    description:
      "Aggregated outstanding-invoice statement emails awaiting human approval.",
    hidden: hideUnlessFeature("nav:invoices"),
  },
  access: {
    read: canAccess("nav:invoices"),
    create: canAccess("nav:invoices"),
    update: canAccess("nav:invoices"),
    delete: canAccess("nav:invoices"),
  },
  defaultSort: "-generatedAt",
  hooks: {
    beforeChange: [
      async ({ data, operation, originalDoc, req }) => {
        // Idempotency hook: at most one `pending` row per `xeroContactId`.
        // Sweep uses `payload.find` to detect an existing pending row and
        // calls `update` instead of `create`, so this hook is a backstop
        // for any other code path (manual admin create, etc.).
        if (operation !== "create") return data;
        if (!data || data.status !== "pending") return data;
        const xeroContactId =
          typeof data.xeroContactId === "string" ? data.xeroContactId : null;
        if (!xeroContactId) return data;
        const existing = await req.payload.find({
          collection: "invoice-statement-drafts" as never,
          where: {
            and: [
              { xeroContactId: { equals: xeroContactId } },
              { status: { equals: "pending" } },
            ],
          } as never,
          limit: 1,
          depth: 0,
          overrideAccess: true,
        });
        if (existing.docs.length > 0) {
          const blockedId =
            (existing.docs[0] as { id: number | string } | undefined)?.id ??
            "(unknown)";
          throw new Error(
            `A pending invoice-statement draft already exists for Xero contact ${xeroContactId} (row #${blockedId}). Update that row instead of creating a new one.`,
          );
        }
        // Avoid an unused-parameter warning when there's no originalDoc to inspect.
        void originalDoc;
        return data;
      },
    ],
  },
  fields: [
    {
      name: "status",
      type: "select",
      required: true,
      defaultValue: "pending",
      index: true,
      options: [
        { label: "Pending review", value: "pending" },
        { label: "Approved & sent", value: "approved" },
        { label: "Rejected", value: "rejected" },
        { label: "Send failed", value: "failed" },
        { label: "Expired (no review)", value: "expired" },
      ],
    },
    {
      name: "generatedAt",
      type: "date",
      required: true,
      index: true,
      admin: { date: { pickerAppearance: "dayAndTime" } },
    },
    {
      name: "xeroContactId",
      type: "text",
      required: true,
      index: true,
      admin: { description: "Upsert key. Stable per Xero contact." },
    },
    {
      name: "contactName",
      type: "text",
      required: true,
      admin: { description: "Denormalised from snapshot for list rendering." },
    },
    {
      name: "recipientEmail",
      type: "text",
      defaultValue: "",
      admin: {
        description:
          "Empty string when the Xero contact has no email \u2014 surfaces in the queue so the gap is visible. Approve & Send is disabled until populated.",
      },
    },
    {
      name: "client",
      type: "relationship",
      relationTo: "clients",
      hasMany: false,
      admin: {
        description:
          "Best-effort case-insensitive name match. May be blank if no client record matches.",
      },
    },
    {
      name: "totalOutstanding",
      type: "number",
      required: true,
      defaultValue: 0,
      admin: { description: "Sum of AmountDue across all unpaid invoices (AUD)." },
    },
    {
      name: "totalOverdue",
      type: "number",
      required: true,
      defaultValue: 0,
    },
    {
      name: "unpaidCount",
      type: "number",
      required: true,
      defaultValue: 0,
    },
    {
      name: "overdueCount",
      type: "number",
      required: true,
      defaultValue: 0,
    },
    {
      name: "snapshot",
      type: "json",
      required: true,
      admin: {
        description:
          "Frozen StatementSnapshot \u2014 contact, unpaid[], paid[], totals, capturedAt.",
      },
    },
    {
      name: "customMessage",
      type: "textarea",
      admin: {
        description:
          "Optional personal note prepended above the invoice table.",
      },
    },
    {
      name: "greetingOverride",
      type: "text",
      admin: {
        description:
          "Override the global greeting for this single draft. Leave blank to use the template greeting. Example: \"Hi team,\".",
      },
    },
    {
      name: "reviewedBy",
      type: "relationship",
      relationTo: "users",
      hasMany: false,
    },
    {
      name: "reviewedAt",
      type: "date",
      admin: { date: { pickerAppearance: "dayAndTime" } },
    },
    {
      name: "sentAt",
      type: "date",
      admin: { date: { pickerAppearance: "dayAndTime" } },
    },
    {
      name: "postmarkMessageId",
      type: "text",
      admin: { description: "Returned by Postmark after a successful send." },
    },
    {
      name: "ccList",
      type: "text",
      admin: {
        description:
          "Snapshot of `statementCcEmails` at send time (comma-separated). For audit.",
      },
    },
    {
      name: "sendError",
      type: "textarea",
      admin: { description: "Populated when `status='failed'`." },
    },
    {
      name: "rejectionReason",
      type: "textarea",
    },
    {
      name: "lastRefreshedAt",
      type: "date",
      admin: {
        description:
          "When the snapshot was last refreshed against Xero. Used to flag stale drafts in the queue.",
        date: { pickerAppearance: "dayAndTime" },
      },
    },
  ],
  timestamps: true,
};
