import { MigrateDownArgs, MigrateUpArgs, sql } from '@payloadcms/db-sqlite'

/**
 * Payload stores hasMany select row IDs as text. The original clients_services
 * migration used INTEGER PRIMARY KEY, which can break client edit pages when
 * Payload tries to read/write the services relation rows.
 */
export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.run(sql`CREATE TABLE IF NOT EXISTS \`clients_services_new\` (
    \`order\` integer NOT NULL,
    \`parent_id\` integer NOT NULL,
    \`value\` text,
    \`id\` text PRIMARY KEY NOT NULL,
    FOREIGN KEY (\`parent_id\`) REFERENCES \`clients\`(\`id\`) ON UPDATE no action ON DELETE cascade
  );`)

  try {
    await db.run(sql`INSERT INTO \`clients_services_new\`
      (\`order\`, \`parent_id\`, \`value\`, \`id\`)
      SELECT \`order\`, \`parent_id\`, \`value\`, CAST(\`id\` AS text)
      FROM \`clients_services\`;`)
  } catch { /* old table missing or empty */ }

  await db.run(sql`DROP TABLE IF EXISTS \`clients_services\`;`)
  await db.run(sql`ALTER TABLE \`clients_services_new\` RENAME TO \`clients_services\`;`)

  await db.run(sql`CREATE INDEX IF NOT EXISTS \`clients_services_order_idx\` ON \`clients_services\` (\`order\`);`)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`clients_services_parent_id_idx\` ON \`clients_services\` (\`parent_id\`);`)
}

export async function down(_args: MigrateDownArgs): Promise<void> {
  // No-op: reverting would risk losing string IDs generated by Payload.
}
