/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    clients: Client;
    'client-proposals': ClientProposal;
    'blog-posts': BlogPost;
    'job-posts': JobPost;
    'seo-audits': SeoAudit;
    'cro-audits': CroAudit;
    'keyword-snapshots': KeywordSnapshot;
    'competitor-analyses': CompetitorAnalysis;
    'content-researches': ContentResearch;
    'usage-reports': UsageReport;
    'gsc-snapshots': GscSnapshot;
    'gsc-alerts': GscAlert;
    'activity-log': ActivityLog;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    'client-proposals': ClientProposalsSelect<false> | ClientProposalsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'job-posts': JobPostsSelect<false> | JobPostsSelect<true>;
    'seo-audits': SeoAuditsSelect<false> | SeoAuditsSelect<true>;
    'cro-audits': CroAuditsSelect<false> | CroAuditsSelect<true>;
    'keyword-snapshots': KeywordSnapshotsSelect<false> | KeywordSnapshotsSelect<true>;
    'competitor-analyses': CompetitorAnalysesSelect<false> | CompetitorAnalysesSelect<true>;
    'content-researches': ContentResearchesSelect<false> | ContentResearchesSelect<true>;
    'usage-reports': UsageReportsSelect<false> | UsageReportsSelect<true>;
    'gsc-snapshots': GscSnapshotsSelect<false> | GscSnapshotsSelect<true>;
    'gsc-alerts': GscAlertsSelect<false> | GscAlertsSelect<true>;
    'activity-log': ActivityLogSelect<false> | ActivityLogSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'manager' | 'specialist';
  /**
   * Whether this user has completed their first-login setup
   */
  setupCompleted?: boolean | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Manage client websites
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  /**
   * Client/business name (e.g., 'Acme Corp')
   */
  name: string;
  /**
   * URL-friendly identifier (e.g., 'acme-corp')
   */
  slug: string;
  /**
   * Client website URL (e.g., 'https://acmecorp.com')
   */
  websiteUrl?: string | null;
  /**
   * API key for this client (auto-generated)
   */
  apiKey?: string | null;
  /**
   * Enable/disable content publishing for this client
   */
  isActive?: boolean | null;
  /**
   * Check if this is the agency itself (hides revenue fields)
   */
  isAgency?: boolean | null;
  /**
   * 4-digit PIN for client hub access (auto-generated)
   */
  clientPin?: string | null;
  /**
   * Who built the website — determines whether GSC alerts are actionable (we fix) or advisory (we recommend)
   */
  websiteType?: ('built_by_us' | 'external_cms') | null;
  /**
   * Which CMS platform is the website built on?
   */
  externalCms?: ('wordpress' | 'shopify' | 'squarespace' | 'wix' | 'webflow' | 'other') | null;
  /**
   * Primary contact name
   */
  contactName?: string | null;
  /**
   * Primary contact email
   */
  contactEmail?: string | null;
  /**
   * Does this business have physical locations?
   */
  hasPhysicalLocations?: boolean | null;
  /**
   * Number of physical locations
   */
  numberOfLocations?: number | null;
  /**
   * Google Maps listing URLs for GBP analysis
   */
  googleMapsUrls?:
    | {
        /**
         * Google Maps listing URL
         */
        url: string;
        /**
         * Location label (e.g. 'Head Office', 'Sydney Branch')
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Primary conversion goal
   */
  conversionGoal?:
    | (
        | 'lead generation'
        | 'phone calls'
        | 'form submissions'
        | 'e-commerce'
        | 'bookings'
        | 'quote requests'
        | 'email sign-ups'
        | 'free trial'
        | 'content downloads'
        | 'brand awareness'
      )
    | null;
  /**
   * Secondary conversion goal
   */
  secondaryConversionGoal?:
    | (
        | 'lead generation'
        | 'phone calls'
        | 'form submissions'
        | 'e-commerce'
        | 'bookings'
        | 'quote requests'
        | 'email sign-ups'
        | 'free trial'
        | 'content downloads'
        | 'brand awareness'
      )
    | null;
  /**
   * Monthly revenue amount ($)
   */
  monthlyRetainer?: number | null;
  /**
   * One-off projects (website builds, audits, etc.)
   */
  oneOffProjects?:
    | {
        /**
         * Project name
         */
        projectName: string;
        /**
         * Project amount ($)
         */
        amount: number;
        /**
         * Project date
         */
        date: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Goals, notes, and context about this client
   */
  notes?: string | null;
  /**
   * Automatic log of revenue changes
   */
  retainerHistory?:
    | {
        amount?: number | null;
        previousAmount?: number | null;
        effectiveDate?: string | null;
        changedBy?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Type of business — used for report weighting and presentation
   */
  businessType?:
    | (
        | 'trades'
        | 'services'
        | 'ecommerce'
        | 'healthcare'
        | 'hospitality'
        | 'realestate'
        | 'education'
        | 'saas'
        | 'other'
      )
    | null;
  /**
   * Primary target location for rankings (e.g., 'Sydney, Australia')
   */
  targetLocation?: string | null;
  /**
   * Client objectives — what they want to achieve (shown in report intro)
   */
  clientGoals?: string | null;
  /**
   * Consolidated keyword list (one per line)
   */
  keywords?: string | null;
  /**
   * Total Addressable Market data
   */
  tam?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Website visitor → lead conversion rate (%)
   */
  leadConversionRate?: number | null;
  /**
   * Lead → paying client conversion rate (%)
   */
  leadToSaleConversionRate?: number | null;
  /**
   * Average order / client value ($)
   */
  averageOrderValue?: number | null;
  /**
   * Annual purchase frequency
   */
  annualPurchaseFrequency?: number | null;
  /**
   * New customers acquired in the last 12 months
   */
  newCustomersLast12Months?: number | null;
  /**
   * Competitor businesses to benchmark against (up to 5)
   */
  competitors?:
    | {
        /**
         * Competitor business name
         */
        name: string;
        /**
         * Competitor website URL
         */
        websiteUrl?: string | null;
        /**
         * Google Maps listing URL for GBP analysis
         */
        googleMapsUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Blog categories for this client (one per line)
   */
  blogCategories?: string | null;
  /**
   * Available tags for this client (one per line)
   */
  blogTags?: string | null;
  /**
   * Author profiles for this client (up to 10)
   */
  authors?:
    | {
        /**
         * Author's display name
         */
        name: string;
        /**
         * Author's job title (e.g., 'Senior SEO Strategist')
         */
        jobTitle?: string | null;
        /**
         * Short bio or description of the author
         */
        blurb?: string | null;
        /**
         * Author's profile photo
         */
        image?: (number | null) | Media;
        /**
         * Tags highlighting this author's areas of expertise
         */
        expertiseTags?:
          | {
              tag: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Social media and website links
         */
        socialLinks?:
          | {
              platform: 'website' | 'linkedin' | 'twitter' | 'facebook' | 'instagram' | 'youtube';
              /**
               * Full URL (e.g., 'https://linkedin.com/in/johndoe')
               */
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Whether Google Search Console is connected
   */
  gscConnected?: boolean | null;
  /**
   * The connected GSC property URL
   */
  gscPropertyUrl?: string | null;
  gscAccessToken?: string | null;
  gscRefreshToken?: string | null;
  gscTokenExpiry?: string | null;
  /**
   * Comma-separated brand terms to filter out from generic query analysis (e.g., 'optimise digital, optimisedigital, od agency')
   */
  brandKeywords?: string | null;
  /**
   * Last successful GSC data sync
   */
  gscLastSync?: string | null;
  /**
   * Most recent GSC data snapshot
   */
  latestGscSnapshot?: (number | null) | GscSnapshot;
  updatedAt: string;
  createdAt: string;
}
/**
 * Upload and manage media. Images: max 800 KB. Videos: max 10 MB (no bulk upload).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for accessibility and SEO. Be specific (e.g., 'Team meeting in modern office with whiteboard').
   */
  alt?: string | null;
  /**
   * Optional caption to display below the image.
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Monthly Google Search Console data snapshots
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gsc-snapshots".
 */
export interface GscSnapshot {
  id: number;
  /**
   * The client this snapshot belongs to
   */
  client: number | Client;
  /**
   * Date this snapshot was taken
   */
  snapshotDate: string;
  /**
   * Start of the reporting period
   */
  periodStart: string;
  /**
   * End of the reporting period
   */
  periodEnd: string;
  /**
   * Total clicks from search
   */
  totalClicks?: number | null;
  /**
   * Total search impressions
   */
  totalImpressions?: number | null;
  /**
   * Average click-through rate (%)
   */
  avgCtr?: number | null;
  /**
   * Average search position
   */
  avgPosition?: number | null;
  /**
   * Top keywords — array of {keyword, clicks, impressions, ctr, position}
   */
  topKeywords?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Top pages — array of {page, clicks, impressions, ctr, position}
   */
  topPages?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Brand query metrics — {clicks, impressions, ctr, position}
   */
  brandedData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Non-brand query metrics — {clicks, impressions, ctr, position, topQueries: [...]}
   */
  nonBrandedData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Number of indexed pages
   */
  indexedPages?: number | null;
  /**
   * Number of pages not indexed
   */
  notIndexedPages?: number | null;
  /**
   * Indexing issues — array of {reason, count, urls}
   */
  indexingIssues?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Sitemaps — array of {url, lastSubmitted, isPending, warnings, errors}
   */
  sitemaps?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Mobile CWV — {lcp, fid, cls, status} where status is GOOD/NEEDS_IMPROVEMENT/POOR
   */
  cwvMobile?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Desktop CWV — {lcp, fid, cls, status}
   */
  cwvDesktop?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Clicks change vs previous period (%)
   */
  clicksChange?: number | null;
  /**
   * Impressions change vs previous period (%)
   */
  impressionsChange?: number | null;
  /**
   * Position change vs previous period (negative = improved)
   */
  positionChange?: number | null;
  /**
   * Previous snapshot for comparison
   */
  previousSnapshot?: (number | null) | GscSnapshot;
  updatedAt: string;
  createdAt: string;
}
/**
 * Proposals for prospective clients
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-proposals".
 */
export interface ClientProposal {
  id: number;
  /**
   * Prospect business name
   */
  businessName: string;
  /**
   * URL-friendly identifier (auto-generated from business name)
   */
  slug: string;
  /**
   * Prospect website URL
   */
  websiteUrl: string;
  /**
   * Primary contact name
   */
  contactName?: string | null;
  /**
   * Primary contact email
   */
  contactEmail?: string | null;
  /**
   * Does this business have physical locations?
   */
  hasPhysicalLocations?: boolean | null;
  /**
   * Number of physical locations
   */
  numberOfLocations?: number | null;
  /**
   * Google Maps listing URLs for GBP analysis
   */
  googleMapsUrls?:
    | {
        /**
         * Google Maps listing URL
         */
        url: string;
        /**
         * Location label (e.g. 'Head Office', 'Sydney Branch')
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Type of business — used for audit weighting
   */
  businessType?:
    | (
        | 'trades'
        | 'services'
        | 'ecommerce'
        | 'healthcare'
        | 'hospitality'
        | 'realestate'
        | 'education'
        | 'saas'
        | 'other'
      )
    | null;
  /**
   * Primary conversion goal — used for CRO audit
   */
  conversionGoal?:
    | (
        | 'lead generation'
        | 'phone calls'
        | 'form submissions'
        | 'e-commerce'
        | 'bookings'
        | 'quote requests'
        | 'email sign-ups'
        | 'free trial'
        | 'content downloads'
        | 'brand awareness'
      )
    | null;
  /**
   * What the prospect wants to achieve
   */
  businessGoals?: string | null;
  /**
   * Internal team notes
   */
  notes?: string | null;
  /**
   * Total Addressable Market data shown on the Mission Brief slide. Leave empty to hide. Supports bold, italic, underline, font size formatting.
   */
  tam?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * CSS selector to click before capturing screenshots (e.g. age-gate 'Enter site' button). Leave blank for most sites.
   */
  screenshotClickSelector?: string | null;
  /**
   * Path or URL to the HTML mockup for this client (e.g. /mockups/purples/index.html)
   */
  websiteMockupUrl?: string | null;
  /**
   * Up to 6 keyword categories (e.g. by service). Each category becomes a separate table on the report. Keywords from all categories are combined for the audit.
   */
  keywordCategories?:
    | {
        /**
         * Category label shown as the table heading (e.g. 'Weight Loss Treatments')
         */
        categoryName: string;
        /**
         * One keyword per line
         */
        keywords: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Legacy single keyword list — use Keyword Categories above instead. Kept for backward compatibility.
   */
  keywords?: string | null;
  /**
   * Location for keyword tracking and competitor analysis
   */
  targetLocation?:
    | (
        | 'au'
        | 'au:sydney'
        | 'au:melbourne'
        | 'au:brisbane'
        | 'au:perth'
        | 'au:adelaide'
        | 'au:canberra'
        | 'au:hobart'
        | 'au:darwin'
        | 'nz'
        | 'nz:auckland'
        | 'nz:wellington'
        | 'us'
        | 'us:new-york'
        | 'us:los-angeles'
        | 'us:chicago'
        | 'us:houston'
        | 'us:miami'
        | 'us:atlanta'
        | 'us:seattle'
        | 'us:denver'
        | 'ca'
        | 'ca:toronto'
        | 'ca:vancouver'
        | 'ca:montreal'
        | 'gb'
        | 'gb:london'
        | 'gb:manchester'
        | 'gb:birmingham'
        | 'sg'
      )
    | null;
  /**
   * One idea per line — these will appear at the bottom of the report as potential recommendations for the prospect
   */
  suggestions?: string | null;
  /**
   * Website visitor → lead conversion rate (%). Used for Mission Control slide.
   */
  leadConversionRate?: number | null;
  /**
   * Lead → paying client conversion rate (%). Used for Mission Control slide.
   */
  leadToSaleConversionRate?: number | null;
  /**
   * Average order / client value ($). Used for Mission Control slide.
   */
  averageOrderValue?: number | null;
  /**
   * Annual purchase frequency (Total orders in last 12 months ÷ Unique customers in last 12 months). Used for CLTV calculation.
   */
  annualPurchaseFrequency?: number | null;
  /**
   * Number of new customers acquired in the last 12 months.
   */
  newCustomersLast12Months?: number | null;
  /**
   * Override monthly visits shown for your business on the report. Leave blank to use API data.
   */
  overrideMonthlyVisits?: number | null;
  /**
   * Override average keyword position. Leave blank to use API data.
   */
  overrideAvgPosition?: number | null;
  /**
   * Override keywords found count. Leave blank to use API data.
   */
  overrideKeywordsFound?: number | null;
  /**
   * Competitor businesses to benchmark against (up to 5)
   */
  competitors?:
    | {
        /**
         * Competitor business name
         */
        name: string;
        /**
         * Competitor website URL
         */
        websiteUrl?: string | null;
        /**
         * Google Maps listing URL
         */
        googleMapsUrl?: string | null;
        /**
         * Override: mark this competitor as running Meta Ads
         */
        hasMetaAds?: boolean | null;
        /**
         * Manual Google Ads screenshots (up to 4). Overrides growth tools data.
         */
        googleAdScreenshots?:
          | {
              image: number | Media;
              id?: string | null;
            }[]
          | null;
        /**
         * Manual Meta Ads screenshots (up to 4). Overrides growth tools data.
         */
        metaAdScreenshots?:
          | {
              image: number | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Current audit pipeline status
   */
  auditStatus?: ('pending' | 'running' | 'completed' | 'failed') | null;
  /**
   * Current stage of the audit pipeline (e.g. 'seo_done|40')
   */
  auditProgress?: string | null;
  /**
   * When audits were last kicked off
   */
  auditStartedAt?: string | null;
  /**
   * When audits finished
   */
  auditCompletedAt?: string | null;
  /**
   * Error details if audits failed
   */
  auditError?: string | null;
  /**
   * Linked SEO audit
   */
  seoAudit?: (number | null) | SeoAudit;
  /**
   * Linked CRO audit
   */
  croAudit?: (number | null) | CroAudit;
  /**
   * Linked keyword snapshot
   */
  keywordSnapshot?: (number | null) | KeywordSnapshot;
  /**
   * Linked competitor analysis
   */
  competitorAnalysis?: (number | null) | CompetitorAnalysis;
  /**
   * Linked content research results
   */
  contentResearch?: (number | ContentResearch)[] | null;
  /**
   * Select slides to REMOVE from the report. Selected slides will be hidden. Leave empty to show all.
   */
  visibleSlides?:
    | (
        | '1'
        | '2'
        | '3'
        | '4'
        | '5'
        | '6'
        | '7'
        | '8'
        | '9'
        | '10'
        | '11'
        | '12'
        | '13'
        | '14'
        | '15'
        | '16'
        | '17'
        | '18'
        | '19'
      )[]
    | null;
  /**
   * Editable flight plan content shown on the report. Supports bold, italic, underline, font size formatting. Falls back to suggestions if empty.
   */
  flightPlan?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Images displayed on the Flight Plan slide above the timeline. Add after the report is created.
   */
  flightPlanImages?:
    | {
        image: number | Media;
        /**
         * Optional caption for this image
         */
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Select which content research keywords to show on the report. Leave empty to auto-select top 2 by search volume.
   */
  contentResearchKeywords?: (number | ContentResearch)[] | null;
  /**
   * Images displayed on the Mission Resources slide. Additional images create extra slides.
   */
  missionResourcesImages?:
    | {
        image: number | Media;
        /**
         * Optional caption for this image
         */
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Content for the Mission Resources slide. Supports bold, italic, underline, font size formatting.
   */
  missionResources?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Content for the Launch Requirements slide. Supports bold, italic, underline, font size formatting.
   */
  launchRequirements?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  excludedCompetitorDomains?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Current stage of this proposal
   */
  proposalStatus?: ('draft' | 'proposal_sent' | 'proposal_presented' | 'client' | 'declined') | null;
  /**
   * Toggle on and save to create an active Client from this proposal
   */
  convertToClient?: boolean | null;
  /**
   * 4-digit PIN for prospect report access (auto-generated)
   */
  proposalPin?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Full SEO audit reports from the growth tools
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-audits".
 */
export interface SeoAudit {
  id: number;
  /**
   * The URL that was audited
   */
  websiteUrl: string;
  businessType: string;
  /**
   * Overall SEO score (0-10)
   */
  overallScore: number;
  /**
   * Number of pages crawled
   */
  pagesAnalyzed?: number | null;
  /**
   * Email captured from gated form (if provided)
   */
  customerEmail?: string | null;
  /**
   * Scores per category (metaData, headingStructure, structuredData, internalLinking, imageOptimization, urlStructure, coreWebVitals, navigationUx, eeat, faqImplementation, contentStructure, serviceCoverage)
   */
  categoryScores:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Per-page breakdown — each entry has url, pageType, scores, and findings
   */
  pageResults?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Cross-page findings — each entry has category, score, status (good/warning/critical), and message
   */
  siteWideFindings?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Prioritised action list — each entry has priority, title, description, impact, and estimatedLift
   */
  recommendations?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Technical data — sitemapFound, robotsTxtFound, schemaTypes, totalInternalLinks, totalImages, imagesWithoutAlt
   */
  extractedData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Custom URL slug for the report (e.g. 'acme-corp-feb-2026'). Auto-generated from website URL if left blank.
   */
  reportSlug?: string | null;
  /**
   * Set a password to protect this report. Share it with the client so they can view the report.
   */
  reportPassword?: string | null;
  /**
   * Link to existing client (optional)
   */
  client?: (number | null) | Client;
  /**
   * Link to client proposal (optional)
   */
  proposal?: (number | null) | ClientProposal;
  /**
   * IP address of the visitor
   */
  visitorIp?: string | null;
  /**
   * Browser fingerprint hash
   */
  visitorFingerprint?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Conversion rate optimisation audit reports from the growth tools
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cro-audits".
 */
export interface CroAudit {
  id: number;
  /**
   * The URL that was audited
   */
  websiteUrl: string;
  /**
   * Primary conversion goal (e.g. lead generation, e-commerce)
   */
  conversionGoal: string;
  /**
   * Overall CRO score (0-10)
   */
  overallScore?: number | null;
  /**
   * Above the fold / trust signals score
   */
  aboveFoldScore?: number | null;
  /**
   * Call-to-action effectiveness score
   */
  ctaScore?: number | null;
  /**
   * Navigation clarity score
   */
  navigationScore?: number | null;
  /**
   * Content structure score
   */
  contentScore?: number | null;
  /**
   * CRO findings — each entry has category, score, status (good/warning/critical), message, and optional details
   */
  findings?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Prioritised recommendations — each entry has priority, title, description, impact, and estimatedLift
   */
  recommendations?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Extracted page content — headline, subHeadlines[], navigationItems[], ctaTexts[]
   */
  extractedContent?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Unique URL slug for this CRO report. Auto-generated if left blank.
   */
  reportSlug?: string | null;
  /**
   * Link to existing client (optional)
   */
  client?: (number | null) | Client;
  /**
   * Link to client proposal (optional)
   */
  proposal?: (number | null) | ClientProposal;
  /**
   * Email captured from gated form (if provided)
   */
  customerEmail?: string | null;
  /**
   * IP address of the visitor
   */
  visitorIp?: string | null;
  /**
   * Browser fingerprint hash
   */
  visitorFingerprint?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Keyword ranking snapshots from the growth tools
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "keyword-snapshots".
 */
export interface KeywordSnapshot {
  id: number;
  /**
   * The website these keywords were tracked for
   */
  websiteUrl: string;
  /**
   * Optional label for this snapshot (e.g. 'February 2026')
   */
  label?: string | null;
  /**
   * Total keywords tracked
   */
  totalKeywords?: number | null;
  /**
   * Keywords ranking in top 10
   */
  top10?: number | null;
  /**
   * Average ranking position
   */
  avgPosition?: number | null;
  /**
   * Number of keyword opportunities
   */
  opportunities?: number | null;
  /**
   * Keyword data — each entry has keyword, position, previousPosition, searchVolume, opportunity, location, lastUpdated
   */
  keywords:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Ranking distribution — { top10, top20, top50, notFound }
   */
  rankingDistribution?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Unique URL slug for this keyword snapshot. Auto-generated if left blank.
   */
  reportSlug?: string | null;
  /**
   * Link to existing client (optional)
   */
  client?: (number | null) | Client;
  /**
   * Link to client proposal (optional)
   */
  proposal?: (number | null) | ClientProposal;
  updatedAt: string;
  createdAt: string;
}
/**
 * Competitor analysis reports
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competitor-analyses".
 */
export interface CompetitorAnalysis {
  id: number;
  /**
   * The website that was analyzed
   */
  websiteUrl: string;
  /**
   * Array of keywords used for the analysis
   */
  keywords?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Location used for the analysis
   */
  location?: string | null;
  /**
   * Number of competitors found
   */
  totalCompetitors?: number | null;
  /**
   * Your site's competitor profile — domain, avgPosition, keywordsFound, traffic
   */
  yourProfile?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Array of competitor profile objects
   */
  competitors?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Unique URL slug for this report. Auto-generated if left blank.
   */
  reportSlug?: string | null;
  /**
   * Link to existing client (optional)
   */
  client?: (number | null) | Client;
  /**
   * Link to client proposal (optional)
   */
  proposal?: (number | null) | ClientProposal;
  updatedAt: string;
  createdAt: string;
}
/**
 * Content research results from the growth tools
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-researches".
 */
export interface ContentResearch {
  id: number;
  /**
   * The keyword researched
   */
  keyword: string;
  /**
   * Location used for research (e.g. 'au')
   */
  location?: string | null;
  /**
   * Total number of questions/topics found
   */
  totalQuestions?: number | null;
  /**
   * Array of topic clusters — each has label (string) and questions (array of { question, source, modifier, searchVolume })
   */
  clusters?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * ID returned by the content research API
   */
  externalId?: string | null;
  /**
   * Link to client proposal
   */
  proposal?: (number | null) | ClientProposal;
  updatedAt: string;
  createdAt: string;
}
/**
 * Create and manage blog posts for clients
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  /**
   * Select which client this blog post belongs to
   */
  client: number | Client;
  /**
   * Confirm the selected client is correct before saving or publishing
   */
  clientConfirmed?: boolean | null;
  /**
   * The H1 title. Make it intent-led: describe what the reader will learn + who it's for.
   */
  title: string;
  /**
   * Brief summary for SEO meta description (max 160 characters). This appears in search results.
   */
  excerpt?: string | null;
  /**
   * Main blog content. Use H2 for main sections, H3 for subsections. See the style guide below.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Estimated reading time (e.g., '5 min read').
   */
  readingTime?: string | null;
  /**
   * Raw markdown content. If provided, this will be used instead of the rich text editor on the website.
   */
  markdownContent?: string | null;
  /**
   * URL slug (e.g., 'how-to-improve-website-speed'). Use hyphens, lowercase, no spaces.
   */
  slug: string;
  /**
   * SEO title for search results (max 60 chars). Leave blank to use the main title.
   */
  metaTitle?: string | null;
  /**
   * SEO description (max 160 chars). Leave blank to use the excerpt.
   */
  metaDescription?: string | null;
  /**
   * Only set if this content exists elsewhere and you want to point to the original.
   */
  canonicalUrl?: string | null;
  /**
   * Click "Generate Prompt" below to create an AI image prompt from your title and excerpt. Review and edit the prompt here, then click "Generate Image".
   */
  imagePromptOverride?: string | null;
  /**
   * Main image for the blog post. Will be used as thumbnail and social sharing image.
   */
  featuredImage?: (number | null) | Media;
  /**
   * Describe the image for accessibility and SEO (e.g., 'Developer working on laptop in office').
   */
  featuredImageAlt?: string | null;
  /**
   * Primary category for this post.
   */
  category?: string | null;
  /**
   * Add relevant tags for filtering and SEO.
   */
  tags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Author name as it should appear on the post.
   */
  author: string;
  /**
   * Publication date (for display and sorting).
   */
  publishedDate: string;
  /**
   * Only 'Published' posts appear on the website.
   */
  status: 'draft' | 'review' | 'published';
  /**
   * Paste a full markdown file here (with frontmatter). On save, the frontmatter will auto-populate the fields above and the body will be stored as markdown content.
   */
  markdownSource?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage open roles displayed on the careers page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-posts".
 */
export interface JobPost {
  id: number;
  /**
   * Select which client this job post belongs to
   */
  client: number | Client;
  /**
   * Confirm the selected client is correct before saving or publishing
   */
  clientConfirmed?: boolean | null;
  /**
   * Job title as it should appear on the careers page (e.g. 'Senior SEO Specialist').
   */
  jobTitle: string;
  /**
   * One-liner summary shown in the job card (max 200 characters).
   */
  excerpt: string;
  /**
   * Full job description — responsibilities, what the role involves, and what success looks like.
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Which department or team this role sits in.
   */
  department: 'seo' | 'paid-media' | 'cro' | 'strategy' | 'development' | 'design' | 'operations';
  /**
   * Type of employment.
   */
  employmentType: 'full-time' | 'part-time' | 'contract' | 'freelance';
  /**
   * Where the role is based (e.g. 'Remote', 'Sydney, AU', 'Hybrid — Melbourne').
   */
  location: string;
  /**
   * URL slug (e.g. 'senior-seo-specialist'). Auto-generated from the job title if left blank.
   */
  slug: string;
  /**
   * Date this role was posted.
   */
  publishedDate: string;
  /**
   * Only 'Published' roles appear on the careers page.
   */
  status: 'draft' | 'published' | 'closed';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Monthly usage and estimated API cost reports from the growth tools
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usage-reports".
 */
export interface UsageReport {
  id: number;
  /**
   * Auto-generated from month/year (e.g. 'February 2026')
   */
  label?: string | null;
  /**
   * Month (1–12)
   */
  month: number;
  /**
   * Year (e.g. 2026)
   */
  year: number;
  /**
   * Total SEO audits this month
   */
  seoAudits?: number | null;
  /**
   * Total CRO audits this month
   */
  croAudits?: number | null;
  /**
   * Total keyword snapshots this month
   */
  keywordSnapshots?: number | null;
  /**
   * Total individual keywords looked up
   */
  totalKeywordsTracked?: number | null;
  /**
   * Breakdown — { serper, moonshot, postmark, total }
   */
  estimatedCosts?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Total estimated cost for the month (AUD)
   */
  totalEstimatedCost?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Alerts triggered by GSC snapshot comparisons
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gsc-alerts".
 */
export interface GscAlert {
  id: number;
  /**
   * The client this alert belongs to
   */
  client: number | Client;
  /**
   * The snapshot that triggered this alert
   */
  snapshot: number | GscSnapshot;
  /**
   * Alert severity level
   */
  severity: 'critical' | 'warning' | 'info';
  /**
   * Alert category
   */
  category: 'indexing' | 'performance' | 'cwv' | 'keyword' | 'sitemap';
  /**
   * Short alert title (e.g., "Indexing dropped 15%")
   */
  title: string;
  /**
   * Detailed explanation of the issue
   */
  description?: string | null;
  /**
   * Whether we can directly fix this (true for "built by us" clients)
   */
  actionable?: boolean | null;
  /**
   * Recommended action to resolve the issue
   */
  recommendation?: string | null;
  /**
   * Whether this alert has been resolved
   */
  resolved?: boolean | null;
  /**
   * When the alert was resolved
   */
  resolvedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Automatic feed of team activity
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-log".
 */
export interface ActivityLog {
  id: number;
  type:
    | 'blog_published'
    | 'seo_audit_completed'
    | 'cro_audit_completed'
    | 'keyword_analysis'
    | 'client_added'
    | 'retainer_changed'
    | 'proposal_created'
    | 'gsc_snapshot';
  title: string;
  description?: string | null;
  /**
   * User who triggered this activity
   */
  user?: (number | null) | User;
  /**
   * Related client
   */
  client?: (number | null) | Client;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'client-proposals';
        value: number | ClientProposal;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'job-posts';
        value: number | JobPost;
      } | null)
    | ({
        relationTo: 'seo-audits';
        value: number | SeoAudit;
      } | null)
    | ({
        relationTo: 'cro-audits';
        value: number | CroAudit;
      } | null)
    | ({
        relationTo: 'keyword-snapshots';
        value: number | KeywordSnapshot;
      } | null)
    | ({
        relationTo: 'competitor-analyses';
        value: number | CompetitorAnalysis;
      } | null)
    | ({
        relationTo: 'content-researches';
        value: number | ContentResearch;
      } | null)
    | ({
        relationTo: 'usage-reports';
        value: number | UsageReport;
      } | null)
    | ({
        relationTo: 'gsc-snapshots';
        value: number | GscSnapshot;
      } | null)
    | ({
        relationTo: 'gsc-alerts';
        value: number | GscAlert;
      } | null)
    | ({
        relationTo: 'activity-log';
        value: number | ActivityLog;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  setupCompleted?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  websiteUrl?: T;
  apiKey?: T;
  isActive?: T;
  isAgency?: T;
  clientPin?: T;
  websiteType?: T;
  externalCms?: T;
  contactName?: T;
  contactEmail?: T;
  hasPhysicalLocations?: T;
  numberOfLocations?: T;
  googleMapsUrls?:
    | T
    | {
        url?: T;
        label?: T;
        id?: T;
      };
  conversionGoal?: T;
  secondaryConversionGoal?: T;
  monthlyRetainer?: T;
  oneOffProjects?:
    | T
    | {
        projectName?: T;
        amount?: T;
        date?: T;
        id?: T;
      };
  notes?: T;
  retainerHistory?:
    | T
    | {
        amount?: T;
        previousAmount?: T;
        effectiveDate?: T;
        changedBy?: T;
        id?: T;
      };
  businessType?: T;
  targetLocation?: T;
  clientGoals?: T;
  keywords?: T;
  tam?: T;
  leadConversionRate?: T;
  leadToSaleConversionRate?: T;
  averageOrderValue?: T;
  annualPurchaseFrequency?: T;
  newCustomersLast12Months?: T;
  competitors?:
    | T
    | {
        name?: T;
        websiteUrl?: T;
        googleMapsUrl?: T;
        id?: T;
      };
  blogCategories?: T;
  blogTags?: T;
  authors?:
    | T
    | {
        name?: T;
        jobTitle?: T;
        blurb?: T;
        image?: T;
        expertiseTags?:
          | T
          | {
              tag?: T;
              id?: T;
            };
        socialLinks?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  gscConnected?: T;
  gscPropertyUrl?: T;
  gscAccessToken?: T;
  gscRefreshToken?: T;
  gscTokenExpiry?: T;
  brandKeywords?: T;
  gscLastSync?: T;
  latestGscSnapshot?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-proposals_select".
 */
export interface ClientProposalsSelect<T extends boolean = true> {
  businessName?: T;
  slug?: T;
  websiteUrl?: T;
  contactName?: T;
  contactEmail?: T;
  hasPhysicalLocations?: T;
  numberOfLocations?: T;
  googleMapsUrls?:
    | T
    | {
        url?: T;
        label?: T;
        id?: T;
      };
  businessType?: T;
  conversionGoal?: T;
  businessGoals?: T;
  notes?: T;
  tam?: T;
  screenshotClickSelector?: T;
  websiteMockupUrl?: T;
  keywordCategories?:
    | T
    | {
        categoryName?: T;
        keywords?: T;
        id?: T;
      };
  keywords?: T;
  targetLocation?: T;
  suggestions?: T;
  leadConversionRate?: T;
  leadToSaleConversionRate?: T;
  averageOrderValue?: T;
  annualPurchaseFrequency?: T;
  newCustomersLast12Months?: T;
  overrideMonthlyVisits?: T;
  overrideAvgPosition?: T;
  overrideKeywordsFound?: T;
  competitors?:
    | T
    | {
        name?: T;
        websiteUrl?: T;
        googleMapsUrl?: T;
        hasMetaAds?: T;
        googleAdScreenshots?:
          | T
          | {
              image?: T;
              id?: T;
            };
        metaAdScreenshots?:
          | T
          | {
              image?: T;
              id?: T;
            };
        id?: T;
      };
  auditStatus?: T;
  auditProgress?: T;
  auditStartedAt?: T;
  auditCompletedAt?: T;
  auditError?: T;
  seoAudit?: T;
  croAudit?: T;
  keywordSnapshot?: T;
  competitorAnalysis?: T;
  contentResearch?: T;
  visibleSlides?: T;
  flightPlan?: T;
  flightPlanImages?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  contentResearchKeywords?: T;
  missionResourcesImages?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  missionResources?: T;
  launchRequirements?: T;
  excludedCompetitorDomains?: T;
  proposalStatus?: T;
  convertToClient?: T;
  proposalPin?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  client?: T;
  clientConfirmed?: T;
  title?: T;
  excerpt?: T;
  content?: T;
  readingTime?: T;
  markdownContent?: T;
  slug?: T;
  metaTitle?: T;
  metaDescription?: T;
  canonicalUrl?: T;
  imagePromptOverride?: T;
  featuredImage?: T;
  featuredImageAlt?: T;
  category?: T;
  tags?: T;
  author?: T;
  publishedDate?: T;
  status?: T;
  markdownSource?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-posts_select".
 */
export interface JobPostsSelect<T extends boolean = true> {
  client?: T;
  clientConfirmed?: T;
  jobTitle?: T;
  excerpt?: T;
  description?: T;
  department?: T;
  employmentType?: T;
  location?: T;
  slug?: T;
  publishedDate?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-audits_select".
 */
export interface SeoAuditsSelect<T extends boolean = true> {
  websiteUrl?: T;
  businessType?: T;
  overallScore?: T;
  pagesAnalyzed?: T;
  customerEmail?: T;
  categoryScores?: T;
  pageResults?: T;
  siteWideFindings?: T;
  recommendations?: T;
  extractedData?: T;
  reportSlug?: T;
  reportPassword?: T;
  client?: T;
  proposal?: T;
  visitorIp?: T;
  visitorFingerprint?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cro-audits_select".
 */
export interface CroAuditsSelect<T extends boolean = true> {
  websiteUrl?: T;
  conversionGoal?: T;
  overallScore?: T;
  aboveFoldScore?: T;
  ctaScore?: T;
  navigationScore?: T;
  contentScore?: T;
  findings?: T;
  recommendations?: T;
  extractedContent?: T;
  reportSlug?: T;
  client?: T;
  proposal?: T;
  customerEmail?: T;
  visitorIp?: T;
  visitorFingerprint?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "keyword-snapshots_select".
 */
export interface KeywordSnapshotsSelect<T extends boolean = true> {
  websiteUrl?: T;
  label?: T;
  totalKeywords?: T;
  top10?: T;
  avgPosition?: T;
  opportunities?: T;
  keywords?: T;
  rankingDistribution?: T;
  reportSlug?: T;
  client?: T;
  proposal?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competitor-analyses_select".
 */
export interface CompetitorAnalysesSelect<T extends boolean = true> {
  websiteUrl?: T;
  keywords?: T;
  location?: T;
  totalCompetitors?: T;
  yourProfile?: T;
  competitors?: T;
  reportSlug?: T;
  client?: T;
  proposal?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-researches_select".
 */
export interface ContentResearchesSelect<T extends boolean = true> {
  keyword?: T;
  location?: T;
  totalQuestions?: T;
  clusters?: T;
  externalId?: T;
  proposal?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usage-reports_select".
 */
export interface UsageReportsSelect<T extends boolean = true> {
  label?: T;
  month?: T;
  year?: T;
  seoAudits?: T;
  croAudits?: T;
  keywordSnapshots?: T;
  totalKeywordsTracked?: T;
  estimatedCosts?: T;
  totalEstimatedCost?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gsc-snapshots_select".
 */
export interface GscSnapshotsSelect<T extends boolean = true> {
  client?: T;
  snapshotDate?: T;
  periodStart?: T;
  periodEnd?: T;
  totalClicks?: T;
  totalImpressions?: T;
  avgCtr?: T;
  avgPosition?: T;
  topKeywords?: T;
  topPages?: T;
  brandedData?: T;
  nonBrandedData?: T;
  indexedPages?: T;
  notIndexedPages?: T;
  indexingIssues?: T;
  sitemaps?: T;
  cwvMobile?: T;
  cwvDesktop?: T;
  clicksChange?: T;
  impressionsChange?: T;
  positionChange?: T;
  previousSnapshot?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gsc-alerts_select".
 */
export interface GscAlertsSelect<T extends boolean = true> {
  client?: T;
  snapshot?: T;
  severity?: T;
  category?: T;
  title?: T;
  description?: T;
  actionable?: T;
  recommendation?: T;
  resolved?: T;
  resolvedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-log_select".
 */
export interface ActivityLogSelect<T extends boolean = true> {
  type?: T;
  title?: T;
  description?: T;
  user?: T;
  client?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}