/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    clients: Client;
    'blog-posts': BlogPost;
    'job-posts': JobPost;
    'seo-audits': SeoAudit;
    'cro-audits': CroAudit;
    'keyword-snapshots': KeywordSnapshot;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'job-posts': JobPostsSelect<false> | JobPostsSelect<true>;
    'seo-audits': SeoAuditsSelect<false> | SeoAuditsSelect<true>;
    'cro-audits': CroAuditsSelect<false> | CroAuditsSelect<true>;
    'keyword-snapshots': KeywordSnapshotsSelect<false> | KeywordSnapshotsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'manager' | 'specialist';
  /**
   * Whether this user has completed their first-login setup
   */
  setupCompleted?: boolean | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Manage client websites
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  /**
   * Client/business name (e.g., 'Acme Corp')
   */
  name: string;
  /**
   * URL-friendly identifier (e.g., 'acme-corp')
   */
  slug: string;
  /**
   * Client website URL (e.g., 'https://acmecorp.com')
   */
  websiteUrl?: string | null;
  /**
   * API key for this client (auto-generated)
   */
  apiKey?: string | null;
  /**
   * Enable/disable content publishing for this client
   */
  isActive?: boolean | null;
  /**
   * 4-digit PIN for client hub access (auto-generated)
   */
  clientPin?: string | null;
  /**
   * Goals, notes, and context about this client
   */
  notes?: string | null;
  /**
   * Blog categories for this client (one per line)
   */
  blogCategories?: string | null;
  /**
   * Available tags for this client (one per line)
   */
  blogTags?: string | null;
  /**
   * Author profiles for this client (up to 10)
   */
  authors?:
    | {
        /**
         * Author's display name
         */
        name: string;
        /**
         * Author's job title (e.g., 'Senior SEO Strategist')
         */
        jobTitle?: string | null;
        /**
         * Short bio or description of the author
         */
        blurb?: string | null;
        /**
         * Author's profile photo
         */
        image?: (number | null) | Media;
        /**
         * Tags highlighting this author's areas of expertise
         */
        expertiseTags?:
          | {
              tag: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Social media and website links
         */
        socialLinks?:
          | {
              platform: 'website' | 'linkedin' | 'twitter' | 'facebook' | 'instagram' | 'youtube';
              /**
               * Full URL (e.g., 'https://linkedin.com/in/johndoe')
               */
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Upload and manage media. Images: max 800 KB. Videos: max 10 MB (no bulk upload).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for accessibility and SEO. Be specific (e.g., 'Team meeting in modern office with whiteboard').
   */
  alt: string;
  /**
   * Optional caption to display below the image.
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Create and manage blog posts for clients
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  /**
   * Select which client this blog post belongs to
   */
  client: number | Client;
  /**
   * The H1 title. Make it intent-led: describe what the reader will learn + who it's for.
   */
  title: string;
  /**
   * Brief summary for SEO meta description (max 160 characters). This appears in search results.
   */
  excerpt: string;
  /**
   * Main blog content. Use H2 for main sections, H3 for subsections. See the style guide below.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Estimated reading time (e.g., '5 min read').
   */
  readingTime?: string | null;
  /**
   * Raw markdown content. If provided, this will be used instead of the rich text editor on the website.
   */
  markdownContent?: string | null;
  /**
   * URL slug (e.g., 'how-to-improve-website-speed'). Use hyphens, lowercase, no spaces.
   */
  slug: string;
  /**
   * SEO title for search results (max 60 chars). Leave blank to use the main title.
   */
  metaTitle?: string | null;
  /**
   * SEO description. Leave blank to use the excerpt.
   */
  metaDescription?: string | null;
  /**
   * Only set if this content exists elsewhere and you want to point to the original.
   */
  canonicalUrl?: string | null;
  /**
   * Main image for the blog post. Will be used as thumbnail and social sharing image.
   */
  featuredImage?: (number | null) | Media;
  /**
   * Describe the image for accessibility and SEO (e.g., 'Developer working on laptop in office').
   */
  featuredImageAlt?: string | null;
  /**
   * Primary category for this post.
   */
  category?: string | null;
  /**
   * Add relevant tags for filtering and SEO.
   */
  tags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Author name as it should appear on the post.
   */
  author: string;
  /**
   * Publication date (for display and sorting).
   */
  publishedDate: string;
  /**
   * Only 'Published' posts appear on the website.
   */
  status: 'draft' | 'review' | 'published';
  /**
   * Paste a full markdown file here (with frontmatter). On save, the frontmatter will auto-populate the fields above and the body will be stored as markdown content.
   */
  markdownSource?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage open roles displayed on the careers page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-posts".
 */
export interface JobPost {
  id: number;
  /**
   * Select which client this job post belongs to
   */
  client: number | Client;
  /**
   * Job title as it should appear on the careers page (e.g. 'Senior SEO Specialist').
   */
  jobTitle: string;
  /**
   * One-liner summary shown in the job card (max 200 characters).
   */
  excerpt: string;
  /**
   * Full job description — responsibilities, what the role involves, and what success looks like.
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Which department or team this role sits in.
   */
  department: 'seo' | 'paid-media' | 'cro' | 'strategy' | 'development' | 'design' | 'operations';
  /**
   * Type of employment.
   */
  employmentType: 'full-time' | 'part-time' | 'contract' | 'freelance';
  /**
   * Where the role is based (e.g. 'Remote', 'Sydney, AU', 'Hybrid — Melbourne').
   */
  location: string;
  /**
   * URL slug (e.g. 'senior-seo-specialist'). Auto-generated from the job title if left blank.
   */
  slug: string;
  /**
   * Date this role was posted.
   */
  publishedDate: string;
  /**
   * Only 'Published' roles appear on the careers page.
   */
  status: 'draft' | 'published' | 'closed';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Full SEO audit reports from the growth tools
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-audits".
 */
export interface SeoAudit {
  id: number;
  /**
   * The URL that was audited
   */
  websiteUrl: string;
  businessType: string;
  /**
   * Overall SEO score (0-10)
   */
  overallScore: number;
  /**
   * Number of pages crawled
   */
  pagesAnalyzed?: number | null;
  /**
   * Email captured from gated form (if provided)
   */
  customerEmail?: string | null;
  /**
   * Scores per category (metaData, headingStructure, structuredData, internalLinking, imageOptimization, urlStructure, coreWebVitals, navigationUx, eeat, faqImplementation, contentStructure, serviceCoverage)
   */
  categoryScores:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Per-page breakdown — each entry has url, pageType, scores, and findings
   */
  pageResults?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Cross-page findings — each entry has category, score, status (good/warning/critical), and message
   */
  siteWideFindings?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Prioritised action list — each entry has priority, title, description, impact, and estimatedLift
   */
  recommendations?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Technical data — sitemapFound, robotsTxtFound, schemaTypes, totalInternalLinks, totalImages, imagesWithoutAlt
   */
  extractedData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Custom URL slug for the report (e.g. 'acme-corp-feb-2026'). Auto-generated from website URL if left blank.
   */
  reportSlug?: string | null;
  /**
   * Set a password to protect this report. Share it with the client so they can view the report.
   */
  reportPassword?: string | null;
  /**
   * Link to existing client (optional)
   */
  client?: (number | null) | Client;
  /**
   * IP address of the visitor
   */
  visitorIp?: string | null;
  /**
   * Browser fingerprint hash
   */
  visitorFingerprint?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Conversion rate optimisation audit reports from the growth tools
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cro-audits".
 */
export interface CroAudit {
  id: number;
  /**
   * The URL that was audited
   */
  websiteUrl: string;
  /**
   * Primary conversion goal (e.g. lead generation, e-commerce)
   */
  conversionGoal: string;
  /**
   * Overall CRO score (0-10)
   */
  overallScore?: number | null;
  /**
   * Above the fold / trust signals score
   */
  aboveFoldScore?: number | null;
  /**
   * Call-to-action effectiveness score
   */
  ctaScore?: number | null;
  /**
   * Navigation clarity score
   */
  navigationScore?: number | null;
  /**
   * Content structure score
   */
  contentScore?: number | null;
  /**
   * CRO findings — each entry has category, score, status (good/warning/critical), message, and optional details
   */
  findings?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Prioritised recommendations — each entry has priority, title, description, impact, and estimatedLift
   */
  recommendations?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Extracted page content — headline, subHeadlines[], navigationItems[], ctaTexts[]
   */
  extractedContent?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Unique URL slug for this CRO report. Auto-generated if left blank.
   */
  reportSlug?: string | null;
  /**
   * Link to existing client (optional)
   */
  client?: (number | null) | Client;
  /**
   * Email captured from gated form (if provided)
   */
  customerEmail?: string | null;
  /**
   * IP address of the visitor
   */
  visitorIp?: string | null;
  /**
   * Browser fingerprint hash
   */
  visitorFingerprint?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Keyword ranking snapshots from the growth tools
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "keyword-snapshots".
 */
export interface KeywordSnapshot {
  id: number;
  /**
   * The website these keywords were tracked for
   */
  websiteUrl: string;
  /**
   * Optional label for this snapshot (e.g. 'February 2026')
   */
  label?: string | null;
  /**
   * Total keywords tracked
   */
  totalKeywords?: number | null;
  /**
   * Keywords ranking in top 10
   */
  top10?: number | null;
  /**
   * Average ranking position
   */
  avgPosition?: number | null;
  /**
   * Number of keyword opportunities
   */
  opportunities?: number | null;
  /**
   * Keyword data — each entry has keyword, position, previousPosition, searchVolume, opportunity, location, lastUpdated
   */
  keywords:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Ranking distribution — { top10, top20, top50, notFound }
   */
  rankingDistribution?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Unique URL slug for this keyword snapshot. Auto-generated if left blank.
   */
  reportSlug?: string | null;
  /**
   * Link to existing client (optional)
   */
  client?: (number | null) | Client;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'job-posts';
        value: number | JobPost;
      } | null)
    | ({
        relationTo: 'seo-audits';
        value: number | SeoAudit;
      } | null)
    | ({
        relationTo: 'cro-audits';
        value: number | CroAudit;
      } | null)
    | ({
        relationTo: 'keyword-snapshots';
        value: number | KeywordSnapshot;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  setupCompleted?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  websiteUrl?: T;
  apiKey?: T;
  isActive?: T;
  clientPin?: T;
  notes?: T;
  blogCategories?: T;
  blogTags?: T;
  authors?:
    | T
    | {
        name?: T;
        jobTitle?: T;
        blurb?: T;
        image?: T;
        expertiseTags?:
          | T
          | {
              tag?: T;
              id?: T;
            };
        socialLinks?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  client?: T;
  title?: T;
  excerpt?: T;
  content?: T;
  readingTime?: T;
  markdownContent?: T;
  slug?: T;
  metaTitle?: T;
  metaDescription?: T;
  canonicalUrl?: T;
  featuredImage?: T;
  featuredImageAlt?: T;
  category?: T;
  tags?: T;
  author?: T;
  publishedDate?: T;
  status?: T;
  markdownSource?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-posts_select".
 */
export interface JobPostsSelect<T extends boolean = true> {
  client?: T;
  jobTitle?: T;
  excerpt?: T;
  description?: T;
  department?: T;
  employmentType?: T;
  location?: T;
  slug?: T;
  publishedDate?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-audits_select".
 */
export interface SeoAuditsSelect<T extends boolean = true> {
  websiteUrl?: T;
  businessType?: T;
  overallScore?: T;
  pagesAnalyzed?: T;
  customerEmail?: T;
  categoryScores?: T;
  pageResults?: T;
  siteWideFindings?: T;
  recommendations?: T;
  extractedData?: T;
  reportSlug?: T;
  reportPassword?: T;
  client?: T;
  visitorIp?: T;
  visitorFingerprint?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cro-audits_select".
 */
export interface CroAuditsSelect<T extends boolean = true> {
  websiteUrl?: T;
  conversionGoal?: T;
  overallScore?: T;
  aboveFoldScore?: T;
  ctaScore?: T;
  navigationScore?: T;
  contentScore?: T;
  findings?: T;
  recommendations?: T;
  extractedContent?: T;
  reportSlug?: T;
  client?: T;
  customerEmail?: T;
  visitorIp?: T;
  visitorFingerprint?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "keyword-snapshots_select".
 */
export interface KeywordSnapshotsSelect<T extends boolean = true> {
  websiteUrl?: T;
  label?: T;
  totalKeywords?: T;
  top10?: T;
  avgPosition?: T;
  opportunities?: T;
  keywords?: T;
  rankingDistribution?: T;
  reportSlug?: T;
  client?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}