import type { Payload, PayloadRequest } from 'payload'
import type { StagedMeetingScheduler } from './meeting-scheduler-tools'

export class MeetingLinkNotFoundError extends Error {
  constructor(kind: 'client' | 'prospect') {
    super(
      `The linked ${kind === 'client' ? 'client' : 'client proposal'} no longer exists. Remove it and try again.`,
    )
    this.name = 'MeetingLinkNotFoundError'
  }
}

/**
 * Writes an admin-confirmed staged meeting scheduler using only the AdminMate
 * field allowlist. Attendee tokens are generated by the collection hook; slots
 * and invites are still run from the scheduler's own buttons.
 */
export async function createMeetingSchedulerFromStaged(
  payload: Payload,
  staged: StagedMeetingScheduler,
  req: PayloadRequest,
): Promise<{ id: number | string; title: string }> {
  let client:
    | { relationTo: 'clients'; value: number }
    | { relationTo: 'client-proposals'; value: number }
    | null = null
  if (staged.link) {
    const id = Number(staged.link.id)
    client =
      staged.link.kind === 'client'
        ? { relationTo: 'clients', value: id }
        : { relationTo: 'client-proposals', value: id }
    const exists = await payload
      .findByID({ collection: client.relationTo, id, depth: 0, overrideAccess: false, req })
      .catch(() => null)
    if (!exists) throw new MeetingLinkNotFoundError(staged.link.kind)
  }

  const created = await payload.create({
    collection: 'meeting-schedulers',
    data: {
      title: staged.title,
      status: 'draft',
      client,
      durationMinutes: staged.durationMinutes,
      meetingTopic: staged.meetingTopic ?? null,
      timezone: staged.timezone,
      dateOverrides: staged.dates.map((row) => ({
        date: row.date,
        enabled: true,
        start: row.start,
        end: row.end,
        preferred: row.preferred ?? '',
      })),
      attendees: staged.attendees.map((attendee) => ({
        name: attendee.name,
        email: attendee.email,
        internalConfirmed: attendee.internalConfirmed,
      })),
    },
    depth: 0,
    overrideAccess: false,
    req,
  })
  return { id: created.id, title: created.title }
}
