/** Additive schema shared by Payload's committed migration and the production /api/migrate runner. No drops/backfills. */
export const inThePictureSchema: readonly [string, string][] = [
  ['blog_ideas', `CREATE TABLE IF NOT EXISTS blog_ideas (
    id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
    client_id integer NOT NULL REFERENCES clients(id) ON DELETE RESTRICT,
    blog_id text NOT NULL UNIQUE,
    priority numeric NOT NULL, blog_idea text NOT NULL,
    suggested_title text, main_point text, key_points text, points_to_avoid text,
    supporting_content text, contributor text, ideal_author text,
    status text NOT NULL, published_slug text, source_updated_at text,
    record_revision numeric NOT NULL, order_revision numeric NOT NULL,
    editor_notes text, linked_post_id integer REFERENCES blog_posts(id) ON DELETE SET NULL,
    updated_at text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
    created_at text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL)`],
  ['blog_ideas_client_idx', 'CREATE INDEX IF NOT EXISTS blog_ideas_client_idx ON blog_ideas(client_id)'],
  ['blog_ideas_blog_id_idx', 'CREATE UNIQUE INDEX IF NOT EXISTS blog_ideas_blog_id_idx ON blog_ideas(blog_id)'],
  ['blog_ideas_linked_post_idx', 'CREATE INDEX IF NOT EXISTS blog_ideas_linked_post_idx ON blog_ideas(linked_post_id)'],
  ['blog_ideas_updated_at_idx', 'CREATE INDEX IF NOT EXISTS blog_ideas_updated_at_idx ON blog_ideas(updated_at)'],
  ['blog_ideas_created_at_idx', 'CREATE INDEX IF NOT EXISTS blog_ideas_created_at_idx ON blog_ideas(created_at)'],
  ['blog_sync_events', `CREATE TABLE IF NOT EXISTS blog_sync_events (
    id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
    event_key text NOT NULL UNIQUE, client_id numeric NOT NULL REFERENCES clients(id) ON DELETE RESTRICT, post_id text NOT NULL, revision text NOT NULL,
    kind text NOT NULL, body text NOT NULL, state text DEFAULT 'pending' NOT NULL,
    attempts numeric DEFAULT 0 NOT NULL, next_attempt text,
    lease_token text, lease_until text, acknowledged_at text, last_error text,
    updated_at text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
    created_at text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL)`],
  ['blog_sync_events_client_id_idx', 'CREATE INDEX IF NOT EXISTS blog_sync_events_client_id_idx ON blog_sync_events(client_id)'],
  ['blog_sync_events_event_key_idx', 'CREATE UNIQUE INDEX IF NOT EXISTS blog_sync_events_event_key_idx ON blog_sync_events(event_key)'],
  ['blog_sync_events_post_id_idx', 'CREATE INDEX IF NOT EXISTS blog_sync_events_post_id_idx ON blog_sync_events(post_id)'],
  ['blog_sync_events_updated_at_idx', 'CREATE INDEX IF NOT EXISTS blog_sync_events_updated_at_idx ON blog_sync_events(updated_at)'],
  ['blog_sync_events_created_at_idx', 'CREATE INDEX IF NOT EXISTS blog_sync_events_created_at_idx ON blog_sync_events(created_at)'],
  ['blog_posts.website_blog_idea_id', 'ALTER TABLE blog_posts ADD website_blog_idea_id text'],
  ['blog_posts.website_category', 'ALTER TABLE blog_posts ADD website_category text'],
  ['blog_posts.website_service_slug', 'ALTER TABLE blog_posts ADD website_service_slug text'],
  ['blog_posts.website_sync_revision', 'ALTER TABLE blog_posts ADD website_sync_revision text'],
  ['_blog_posts_v.version_website_blog_idea_id', 'ALTER TABLE _blog_posts_v ADD version_website_blog_idea_id text'],
  ['_blog_posts_v.version_website_category', 'ALTER TABLE _blog_posts_v ADD version_website_category text'],
  ['_blog_posts_v.version_website_service_slug', 'ALTER TABLE _blog_posts_v ADD version_website_service_slug text'],
  ['_blog_posts_v.version_website_sync_revision', 'ALTER TABLE _blog_posts_v ADD version_website_sync_revision text'],
  ['locked_docs_rels.blog_ideas_id', 'ALTER TABLE payload_locked_documents_rels ADD blog_ideas_id integer REFERENCES blog_ideas(id) ON DELETE cascade'],
  ['locked_docs_rels.blog_sync_events_id', 'ALTER TABLE payload_locked_documents_rels ADD blog_sync_events_id integer REFERENCES blog_sync_events(id) ON DELETE cascade'],
  ['payload_locked_documents_rels_blog_ideas_id_idx', 'CREATE INDEX IF NOT EXISTS payload_locked_documents_rels_blog_ideas_id_idx ON payload_locked_documents_rels(blog_ideas_id)'],
  ['payload_locked_documents_rels_blog_sync_events_id_idx', 'CREATE INDEX IF NOT EXISTS payload_locked_documents_rels_blog_sync_events_id_idx ON payload_locked_documents_rels(blog_sync_events_id)'],
]
